### ISSUE TITLE
Navigation Crash - iOS

### ISSUE THREAD

**Issue by OudomMunint** [OudomMunint/.NetMAUI-To-Do-List-App#236]
When first installed after continuing from the Welcome page > Dashboard page the app crashes.

**Unhandled Exception:**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.WillMoveToParentViewController(UIViewController parent)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at ToDoListApp.Program.Main(String[] args) in /Users/dom/Documents/GitHub Repos/NetMAUI-To-Do-List-App/Platforms/iOS/Program.cs:line 13
Thread started: <Thread Pool> #14
2024-08-04 15:04:33.574 ToDoListApp[15548:617024] Unhandled managed exception: Object reference not set to an instance of an object. (System.NullReferenceException)
   at Microsoft.Maui.Controls.Handlers.Compatibility.NavigationRenderer.ParentingViewController.WillMoveToParentViewController(UIViewController parent)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 58
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:line 94
   at ToDoListApp.Program.Main(String[] args) in /Users/dom/Documents/GitHub Repos/NetMAUI-To-Do-List-App/Platforms/iOS/Program.cs:line 13
```

**Comment by OudomMunint** [comment]
Fixed by PR #237
